# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBbQy1T9w4asABZbh2qHUGxxQoAxrwIu
"""

!pip install streamlit
import streamlit as st
import torch
import torch.nn as nn
import numpy as np
import cv2
from PIL import Image
# The following functions/classes are defined in other cells and are available in the notebook's global scope.
# from dataset_generator import create_cubesat_silhouette, create_hubble_silhouette, create_iss_silhouette, apply_optical_degradation
# from train_model import SpacecraftCNN

st.set_page_config(page_title="Spacecraft AI Light-Sensor Simulator", layout="wide")
st.title("🛰️ Spacecraft Vision: Low-Light & Turbulence AI Classifier")
st.markdown("""
This tool simulates ground-based telescope observations of spacecraft through turbulent atmospheric and noisy sensor conditions.
""")

# Sidebar Configuration
st.sidebar.header("🔧 Optical Simulation Controls")
selected_spacecraft = st.sidebar.selectbox("Select Target Spacecraft:", ["CubeSat", "Space Telescope (Hubble)", "Space Station (ISS)"])

st.sidebar.markdown("---")
st.sidebar.subheader("🌌 Sensor & Atmospheric Parameters")
noise_std = st.sidebar.slider("Sensor Noise (Gaussian Std Dev):", 0, 50, 20)
blur_kernel = st.sidebar.slider("Atmospheric Blur (Gaussian Kernel Size):", 1, 15, 3, step=2)
contrast_scale = st.sidebar.slider("Optical Contrast Scale:", 0.1, 1.0, 0.5, step=0.05)

# Render base silhouettes
if selected_spacecraft == "CubeSat":
    clean_img = create_cubesat_silhouette()
    actual_label = 0
elif selected_spacecraft == "Space Telescope (Hubble)":
    clean_img = create_hubble_silhouette()
    actual_label = 1
else:
    clean_img = create_iss_silhouette()
    actual_label = 2

# Degrade the image on-the-fly based on slider values
degraded_img = apply_optical_degradation(clean_img, noise_std=noise_std, blur_kernel=blur_kernel, contrast_scale=contrast_scale)

col1, col2, col3 = st.columns([1, 1, 1.2])
with col1:
    st.subheader("🟢 Clean 2D Profile")
    st.image(clean_img, width=250, caption="Reference Silhouette")

with col2:
    st.subheader("🔵 Degraded Observation")
    st.image(degraded_img, width=250, caption="Simulated Telescope View")

# Load model weights
@st.cache_resource
def load_trained_model():
    model = SpacecraftCNN()
    try:
        model.load_state_dict(torch.load("spacecraft_model.pth", map_location=torch.device('cpu')))
    except FileNotFoundError:
        st.warning("Model weights 'spacecraft_model.pth' not found. Training model may be required.")
    model.eval()
    return model

model = load_trained_model()

# Process image for model inference
img_input = degraded_img.astype(np.float32) / 255.0
img_tensor = torch.tensor(img_input).unsqueeze(0).unsqueeze(0) # Formats shape to [10]

with col3:
    st.subheader("🧠 Real-Time AI Prediction")
    with torch.no_grad():
        outputs = model(img_tensor)
        probabilities = torch.nn.functional.softmax(outputs, dim=1).numpy()
        predicted_idx = np.argmax(probabilities)
        confidence = probabilities[0, predicted_idx] * 100 # Extract scalar confidence

    classes = ["CubeSat", "Space Telescope (Hubble)", "Space Station (ISS)"]
    predicted_class = classes[predicted_idx]

    if predicted_idx == actual_label:
        st.success(f"**Prediction: {predicted_class} ({confidence:.2f}%)**")
        st.info("🎯 Correct Classification!")
    else:
        st.error(f"**Prediction: {predicted_class} ({confidence:.2f}%)**")
        st.warning(f"⚠️ Incorrect Classification!")

    st.markdown("### Model Class Probability Breakdowns:")
    for cls, prob in zip(classes, probabilities[0]): # Iterate over the first (and only) row of probabilities
        st.progress(float(prob))
        st.write(f"{cls}: {prob*100:.1f}%")