# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zixGCRyu0Yqch9PiUCcX5TWY10DSnIbW
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import os
import cv2
from scipy.ndimage import gaussian_filter

# --- Start of dataset_generator content ---
def create_cubesat_silhouette(size=(64, 64)):
    img = np.zeros(size, dtype=np.uint8)
    center_x, center_y = size[1] // 2, size[0] // 2
    cv2.rectangle(img, (center_x - 10, center_y - 10), (center_x + 10, center_y + 10), 255, -1)
    return img

def create_hubble_silhouette(size=(64, 64)):
    img = np.zeros(size, dtype=np.uint8)
    center_x, center_y = size[1] // 2, size[0] // 2
    cv2.circle(img, (center_x, center_y), 20, 255, -1)
    cv2.rectangle(img, (center_x - 5, center_y - 25), (center_x + 5, center_y + 25), 255, -1)
    return img

def create_iss_silhouette(size=(64, 64)):
    img = np.zeros(size, dtype=np.uint8)
    center_x, center_y = size[1] // 2, size[0] // 2
    cv2.rectangle(img, (center_x - 20, center_y - 5), (center_x + 20, center_y + 5), 255, -1)
    cv2.rectangle(img, (center_x - 5, center_y - 20), (center_x + 5, center_y + 20), 255, -1)
    return img

def apply_optical_degradation(image, noise_std=10, blur_kernel=3, contrast_scale=0.5):
    img = image.astype(np.float32)

    # Add Gaussian noise
    noise = np.random.normal(0, noise_std, img.shape)
    img_noisy = img + noise

    # Apply blur
    if blur_kernel > 1:
        img_blurred = gaussian_filter(img_noisy, sigma=blur_kernel / 3.0) # sigma relates to kernel size
    else:
        img_blurred = img_noisy

    # Adjust contrast
    mean = np.mean(img_blurred)
    img_contrasted = (img_blurred - mean) * contrast_scale + mean

    # Clip to valid range [0, 255] for image processing
    img_final = np.clip(img_contrasted, 0, 255)

    return img_final.astype(np.uint8)
# --- End of dataset_generator content ---

class SpacecraftDataset(Dataset):
    def __init__(self, num_samples_per_class=300, is_train=True):
        self.data = []
        self.labels = []
        silhouettes = {0: create_cubesat_silhouette(), 1: create_hubble_silhouette(), 2: create_iss_silhouette()}
        np.random.seed(42 if is_train else 100)

        for class_idx, base_img in silhouettes.items():
            for _ in range(num_samples_per_class):
                # Randomize atmospheric parameters for robust generalization
                noise = np.random.uniform(5, 35)
                blur = np.random.choice([1, 9, 10])
                contrast = np.random.uniform(0.2, 0.8)

                degraded = apply_optical_degradation(base_img, noise_std=noise, blur_kernel=blur, contrast_scale=contrast)
                img_tensor = np.expand_dims(degraded.astype(np.float32) / 255.0, axis=0) # Shape: [1, H, W]

                self.data.append(img_tensor)
                self.labels.append(class_idx)

        self.data = np.array(self.data, dtype=np.float32)
        self.labels = np.array(self.labels, dtype=np.int64)

    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        return torch.tensor(self.data[idx]), torch.tensor(self.labels[idx])

class SpacecraftCNN(nn.Module):
    def __init__(self):
        super(SpacecraftCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=3, padding=1)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, padding=1)
        self.pool2 = nn.MaxPool2d(2, 2)
        # Input image size is 64x64. After two pooling layers (2x2), it becomes 16x16.
        self.fc1 = nn.Linear(32 * 16 * 16, 64)
        self.fc2 = nn.Linear(64, 3)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.25)

    def forward(self, x):
        x = self.pool1(self.relu(self.conv1(x)))
        x = self.pool2(self.relu(self.conv2(x)))
        x = x.view(-1, 32 * 16 * 16) # Flatten the output for the fully connected layers
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

def train():
    train_dataset = SpacecraftDataset(num_samples_per_class=300, is_train=True)
    val_dataset = SpacecraftDataset(num_samples_per_class=50, is_train=False)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

    model = SpacecraftCNN()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    print("Training model...")
    for epoch in range(8):
        model.train()
        running_loss = 0.0
        for images, labels in train_loader:
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * images.size(0)

        # Quick validation
        model.eval()
        val_correct, val_total = 0, 0
        with torch.no_grad():
            for v_imgs, v_lbls in val_loader:
                v_outs = model(v_imgs)
                _, v_pred = torch.max(v_outs, 1)
                val_total += v_lbls.size(0)
                val_correct += (v_pred == v_lbls).sum().item()

        print(f"Epoch {epoch+1}/8 | Loss: {running_loss/len(train_dataset):.4f} | Val Accuracy: {val_correct/val_total*100:.1f}%")

    torch.save(model.state_dict(), "spacecraft_model.pth")
    print("✅ Training complete. Weights saved to 'spacecraft_model.pth'")

if __name__ == "__main__":
    train()